services:
  mhcquant:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: mhcquant
    container_name: mhcquant
    restart: always
    ports:
      - 8501:8501
    volumes:
      - workspaces-mhcquant:/workspaces-mhcquant
volumes:
  workspaces-mhcquant:
