name: Docker Image CI

on:
  push:
    branches: [ "main" , "mhcquant", "mhcquant_held_back" ]
  pull_request:
    branches: [ "main" , "mhcquant", "mhcquant_held_back" ]

jobs:

  build-full-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the full Docker image
      run: docker build . --file Dockerfile --tag streamlitapp:latest